on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    ## Run once an hour
    - cron:  '0 * * * *'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::ggplot2
            any::reactable
            any::patchwork
            any::dplyr
            any::tidyr
            any::knitr
          needs: |
            ggplot2
            reactable
            patchwork
            dplyr
            tidyr
            knitr

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          