on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    ## Run once every 10 minutes
    - cron:  '*/10 * * * *'

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-packages
          
      - name: Install R dependencies
        run: |
          pkgs <- c("ggplot2", "reactable", "patchwork", "dplyr", "tidyr", "knitr")
          pkgs <- pkgs[!sapply(pkgs, FUN = requireNamespace)]
          install.packages(pkgs)
        shell: Rscript {0}

      - name: Session information
        run: |
          quarto --version
          Rscript --version

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
